from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class VariableRole(StrEnum):
    """Role of a variable in the causal growth model."""

    CONFOUNDER = "confounder"
    TREATMENT = "treatment"
    MEDIATOR = "mediator"
    OUTCOME = "outcome"
    IDENTIFIER = "identifier"
    TIME = "time"


@dataclass(frozen=True)
class CausalVariable:
    """Definition of a variable in the CGE causal graph."""

    name: str
    role: VariableRole
    description: str


@dataclass(frozen=True)
class CausalEdge:
    """Directed causal relationship between two variables."""

    source: str
    target: str


VARIABLES: tuple[CausalVariable, ...] = (
    CausalVariable(
        name="title_id",
        role=VariableRole.IDENTIFIER,
        description="Product/title identifier.",
    ),
    CausalVariable(
        name="date",
        role=VariableRole.TIME,
        description="Observation date.",
    ),
    CausalVariable(
        name="product_age_days",
        role=VariableRole.TIME,
        description="Number of days since the title entered the observation period.",
    ),
    CausalVariable(
        name="market_demand",
        role=VariableRole.CONFOUNDER,
        description=(
            "Underlying market demand affecting both business decisions and organic acquisition."
        ),
    ),
    CausalVariable(
        name="paid_ua_spend",
        role=VariableRole.TREATMENT,
        description="Daily paid user-acquisition spend.",
    ),
    CausalVariable(
        name="influencer_spend",
        role=VariableRole.TREATMENT,
        description="Daily influencer marketing spend.",
    ),
    CausalVariable(
        name="social_media_posts",
        role=VariableRole.TREATMENT,
        description="Number of social media posts published per day.",
    ),
    CausalVariable(
        name="product_test_release",
        role=VariableRole.TREATMENT,
        description="Number of product test releases deployed per day.",
    ),
    CausalVariable(
        name="product_version_update",
        role=VariableRole.TREATMENT,
        description="Number of product version updates deployed per day.",
    ),
    CausalVariable(
        name="influencer_contracts",
        role=VariableRole.MEDIATOR,
        description=(
            "Number of influencer contracts awarded/activated; an upstream "
            "operational driver of influencer spend."
        ),
    ),
    CausalVariable(
        name="paid_installs",
        role=VariableRole.MEDIATOR,
        description="Installs attributable to paid user acquisition.",
    ),
    CausalVariable(
        name="social_media_likes",
        role=VariableRole.MEDIATOR,
        description="Daily social media likes generated by marketing and demand.",
    ),
    CausalVariable(
        name="social_media_comments",
        role=VariableRole.MEDIATOR,
        description="Daily social media comments generated by social engagement.",
    ),
    CausalVariable(
        name="app_store_rating",
        role=VariableRole.MEDIATOR,
        description=("Product rating affected by product changes and persistent over time."),
    ),
    CausalVariable(
        name="organic_installs",
        role=VariableRole.OUTCOME,
        description="Daily installs not directly attributed to paid acquisition.",
    ),
    CausalVariable(
        name="engagement",
        role=VariableRole.OUTCOME,
        description="User engagement measure downstream of organic acquisition.",
    ),
    CausalVariable(
        name="retention",
        role=VariableRole.OUTCOME,
        description="User retention measure downstream of engagement.",
    ),
    CausalVariable(
        name="revenue",
        role=VariableRole.OUTCOME,
        description="Daily product revenue.",
    ),
)


EDGES: tuple[CausalEdge, ...] = (
    # Market demand creates treatment endogeneity.
    CausalEdge("market_demand", "paid_ua_spend"),
    CausalEdge("market_demand", "influencer_contracts"),
    CausalEdge("market_demand", "social_media_posts"),
    CausalEdge("market_demand", "social_media_likes"),
    CausalEdge("market_demand", "organic_installs"),
    # Influencer operational pathway.
    CausalEdge("influencer_contracts", "influencer_spend"),
    # Paid acquisition pathway.
    CausalEdge("paid_ua_spend", "paid_installs"),
    CausalEdge("paid_installs", "social_media_likes"),
    # Social activity pathway.
    CausalEdge("social_media_posts", "social_media_likes"),
    CausalEdge("influencer_spend", "social_media_likes"),
    CausalEdge("social_media_likes", "social_media_comments"),
    # Product changes affect product rating.
    CausalEdge("product_test_release", "app_store_rating"),
    CausalEdge("product_version_update", "app_store_rating"),
    # Direct treatment effects on organic acquisition.
    CausalEdge("paid_ua_spend", "organic_installs"),
    CausalEdge("influencer_spend", "organic_installs"),
    CausalEdge("social_media_posts", "organic_installs"),
    CausalEdge("product_test_release", "organic_installs"),
    CausalEdge("product_version_update", "organic_installs"),
    # Mediated effects on organic acquisition.
    CausalEdge("social_media_likes", "organic_installs"),
    CausalEdge("social_media_comments", "organic_installs"),
    CausalEdge("app_store_rating", "organic_installs"),
    # Growth funnel.
    CausalEdge("organic_installs", "engagement"),
    CausalEdge("engagement", "retention"),
    CausalEdge("organic_installs", "revenue"),
    CausalEdge("paid_installs", "revenue"),
    CausalEdge("engagement", "revenue"),
    CausalEdge("retention", "revenue"),
)


VARIABLE_BY_NAME: dict[str, CausalVariable] = {variable.name: variable for variable in VARIABLES}


TREATMENTS: tuple[str, ...] = (
    "paid_ua_spend",
    "influencer_spend",
    "social_media_posts",
    "product_test_release",
    "product_version_update",
)


MEDIATORS: tuple[str, ...] = (
    "influencer_contracts",
    "paid_installs",
    "social_media_likes",
    "social_media_comments",
    "app_store_rating",
)


OUTCOMES: tuple[str, ...] = (
    "organic_installs",
    "engagement",
    "retention",
    "revenue",
)


CONFOUNDERS: tuple[str, ...] = ("market_demand",)


def get_parents(variable: str) -> tuple[str, ...]:
    """Return the direct causal parents of a variable."""

    return tuple(edge.source for edge in EDGES if edge.target == variable)


def get_children(variable: str) -> tuple[str, ...]:
    """Return the direct causal children of a variable."""

    return tuple(edge.target for edge in EDGES if edge.source == variable)


def get_variable(variable: str) -> CausalVariable:
    """Return the causal variable definition by name."""

    try:
        return VARIABLE_BY_NAME[variable]
    except KeyError as exc:
        raise KeyError(f"Unknown causal variable: {variable}") from exc


def validate_dag() -> None:
    """Validate the structural consistency of the causal specification."""

    variable_names = set(VARIABLE_BY_NAME)

    if len(variable_names) != len(VARIABLES):
        raise ValueError("Causal variable names must be unique.")

    for edge in EDGES:
        if edge.source not in variable_names:
            raise ValueError(f"Unknown edge source: {edge.source}")

        if edge.target not in variable_names:
            raise ValueError(f"Unknown edge target: {edge.target}")

        if edge.source == edge.target:
            raise ValueError(f"Self-referential causal edge: {edge.source}")

    for treatment in TREATMENTS:
        variable = get_variable(treatment)
        if variable.role != VariableRole.TREATMENT:
            raise ValueError(
                f"{treatment} is listed as a treatment but has role {variable.role.value}."
            )

    for mediator in MEDIATORS:
        variable = get_variable(mediator)
        if variable.role != VariableRole.MEDIATOR:
            raise ValueError(
                f"{mediator} is listed as a mediator but has role {variable.role.value}."
            )

    for outcome in OUTCOMES:
        variable = get_variable(outcome)
        if variable.role != VariableRole.OUTCOME:
            raise ValueError(
                f"{outcome} is listed as an outcome but has role {variable.role.value}."
            )

    for confounder in CONFOUNDERS:
        variable = get_variable(confounder)
        if variable.role != VariableRole.CONFOUNDER:
            raise ValueError(
                f"{confounder} is listed as a confounder but has role {variable.role.value}."
            )


validate_dag()
